{{- if .Values.quota.enabled }}
apiVersion: v1
kind: ResourceQuota
metadata:
  name: {{ include "mercutio.fullname" . }}-cells
  labels:
    {{- include "mercutio.labels" . | nindent 4 }}
spec:
  hard:
    pods: {{ .Values.quota.pods | quote }}
    requests.cpu: {{ .Values.quota.cpu | quote }}
    limits.cpu: {{ .Values.quota.cpu | quote }}
    requests.memory: {{ .Values.quota.memory | quote }}
    limits.memory: {{ .Values.quota.memory | quote }}
{{- end }}
